services:
  bdfr:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bdfr
    volumes:
      - /your/config/location:/config/config.cfg
      - /your/download/location:/downloads 
      - /your/option/location/:/config/options.yaml 
    ports: 
      - 7634:7634
    environment:
      PUID: 1000 # Should be the owner of volumes
      PGID: 1000 # Should be the owner of volumes
      BDFR_POSTLIMIT: 9999 
      BDFR_OFFSET: -1 
      BDFR_WAIT: 300
      BDFR_AUTH: false
      BDFR_VERBOSE: 0 
      BDFR_NODUPES: true
      BDFR_SORT: new
      BDFR_DETOX: false 
      BDFR_RDFIND: false
      BDFR_SYMLINKS: false 
      BDFR_DOWNLOAD_MODE: 0